### ISSUE TITLE
Can you please clarify why you chose a vocabilary size of 50k

### ISSUE THREAD

**Issue by issam9** [alger-ia/dziribert#2]

**Comment by amineabdaoui** [comment]
Hi @issam9 

I think that 50k is a common vocab size for monolingual transformers. 
The original english BERT has 30k tokens [(Devlin et al., 2018)](https://arxiv.org/pdf/1810.04805.pdf), but we usually can improve the quality of the model by adding more tokens [(Conneau et al., 2019)](https://aclanthology.org/2020.acl-main.747.pdf). 
On the other hand, adding more tokens in the vocab will result in a larger model since most of the model weights are located in the embeddings [(Abdaoui et al., 2020)](https://arxiv.org/ftp/arxiv/papers/2010/2010.05609.pdf). 

So it's basically a trade-off between the model size and performance. In our case, we also pre-trained a model with 30k tokens but the results on downstream tasks were slightly lower. 

Sorry for my late reply !

**Comment by issam9** [comment]
Thanks, i really thought that reducing the vocab size will improve the results, especially in this case where the pretraining dataset is relatively small.
I think with a larger vocab size you need a larger dataset to learn a descent representation for each token. But since you tested with a smaller vocab size then i have nothing to say. 

Good job.

**Comment by amineabdaoui** [comment]
Yes, I see your point. 
We still have few checkpoints with a 30k vocab that we can share with you. They may give better results on other downstream datasets. 
The difference on Twifil was very small anyway.

**Comment by issam9** [comment]
That would be great. Thank you.

**Comment by amineabdaoui** [comment]
Here is a version with 30k tokens: https://drive.google.com/drive/folders/1OwGNJmf4uaeZY5HUTcThrdAm1l4abx0X
